[package]
name = "maps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype-rs = "0.32.0"
gl = "0.14.0"
glfw = "0.51.0"
image = "0.24.5"
